apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmyshow
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bookmyshow
  template:
    metadata:
      labels:
        app: bookmyshow
    spec:
      containers:
      - name: bookmyshow
        image: sridatta5157/bookmyshowproj:latest
        ports:
        - containerPort: 3000
